server {
    # Timeout settings
    client_header_timeout 10s;
    client_body_timeout 10s;
    keepalive_timeout 60s;
    send_timeout 60s;

    # FastCGI
    fastcgi_connect_timeout 20s;
    fastcgi_send_timeout 120s;
    fastcgi_read_timeout 1000s;

    listen 80;
    server_name localhost;
    root /var/www/public;

    index index.php index.html;

    gzip on;
    gzip_types text/plain application/json application/javascript text/css application/xml;
    gzip_min_length 256;

    location /build/ {
        alias /var/www/public/build/;
        try_files $uri $uri/ =404;
        access_log off;
        expires 30d;
        add_header Cache-Control "public";
    }

    location ~ \.php$ {
        fastcgi_pass levelup_store_app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        fastcgi_param HTTP_PROXY "";
        fastcgi_intercept_errors off;
        fastcgi_ignore_client_abort off;

        include fastcgi_params;
    }

    location / {
        try_files $uri /index.php$is_args$args;

        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
            expires 7d;
            add_header Cache-Control "public, no-transform";
            access_log off;
            try_files $uri =404;
        }
    }

    location ~ /\.(?!well-known).* {
        deny all;
        access_log off;
        log_not_found off;
    }

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }
}
