services:
  _defaults:
    autowire: true

  # 🚦 Rate Limiter
  App\Infrastructure\RateLimiter\LoginRateLimiter:
    class: App\Infrastructure\RateLimiter\RateLimiter
    arguments:
      $cache: '@cache.app'
      $keyPrefix: 'login'

  App\Infrastructure\RateLimiter\SignupRateLimiter:
    class: App\Infrastructure\RateLimiter\RateLimiter
    arguments:
      $cache: '@cache.app'
      $keyPrefix: 'signup'

  App\Infrastructure\RateLimiter\ForgotPasswordRateLimiter:
    class: App\Infrastructure\RateLimiter\RateLimiter
    arguments:
      $cache: '@cache.app'
      $keyPrefix: 'forgot_password'
