services:
  _defaults:
    autowire: true

  # 🚦 Rate Limiter
  rate_limiter.login:
    class: App\Infrastructure\Shared\RateLimiter\RateLimiter
    arguments:
      $cache: '@cache.app'
      $keyPrefix: 'login'

  rate_limiter.signup:
    class: App\Infrastructure\Shared\RateLimiter\RateLimiter
    arguments:
      $cache: '@cache.app'
      $keyPrefix: 'signup'

  rate_limiter.forgot_password:
    class: App\Infrastructure\Shared\RateLimiter\RateLimiter
    arguments:
      $cache: '@cache.app'
      $keyPrefix: 'forgot_password'
