apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "levelup-store.fullname" . }}-migrate
  labels:
    {{- include "levelup-store.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Force=true
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: migrate
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          command:
            - php
            - /var/www/bin/console
            - doctrine:migrations:migrate
            - --no-interaction
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          envFrom:
            - configMapRef:
                name: {{ include "levelup-store.fullname" . }}
            - secretRef:
                name: {{ include "levelup-store.fullname" . }}
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
