apiVersion: v2
name: tempo
description: Grafana Tempo - distributed tracing backend
type: application
version: 0.1.0

dependencies:
  - name: tempo
    version: ">=1.10.0 <2.0.0"
    repository: https://grafana.github.io/helm-charts
