# ──────────────────────────────────────────────────────────────────────────────────────────────
# 🧱 Base Stack (prod-ready)
# ──────────────────────────────────────────────────────────────────────────────────────────────

include:
  # Database
  - docker/compose/services/database/postgres.yml
  - docker/compose/services/database/elasticsearch.yml

  # Cache
  - docker/compose/services/cache/redis.yml

  # Messaging
  - docker/compose/services/messaging/rabbitmq.yml

  # Storage
  - docker/compose/services/storage/minio.yml

  # Realtime
  - docker/compose/services/realtime/mercure.yml

  # Observability
  - docker/compose/services/observability/prometheus.yml
  - docker/compose/services/observability/alerts.yml
  - docker/compose/services/observability/loki.yml
  - docker/compose/services/observability/alloy.yml
  - docker/compose/services/observability/grafana.yml

  # App
  - docker/compose/services/app/app.yml
  - docker/compose/services/app/cron.yml
  - docker/compose/services/app/worker.yml
  - docker/compose/services/app/webserver.yml

# ──────────────────────────────────────────────────────────────────────────────────────────────
# 🕸️ Networks & Volumes
# ──────────────────────────────────────────────────────────────────────────────────────────────

networks:
  app-network:
    driver: bridge

volumes:
  pg_data:
    driver: local
  elasticsearch_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local
  prometheus_data:
    driver: local
  alertmanager_data:
    driver: local
  loki_data:
    driver: local
  grafana_data:
    driver: local
  minio_data:
    driver: local
  mercure_data:
    driver: local
  mercure_config:
    driver: local
