# ──────────────────────────────────────────────────────────────────────────────────────────────
# 🧑‍💻 Dev-Only Services
#
# Extends docker-compose.yml with local development tools.
#
# Run with:
#   make dev
#   docker compose -f docker-compose.yml -f docker-compose.dev.yml up
# ──────────────────────────────────────────────────────────────────────────────────────────────

include:
  - docker/compose/services/_dev/pgAdmin.yml
  - docker/compose/services/_dev/elasticvue.yml
  - docker/compose/services/_dev/mailpit.yml
  - docker/compose/services/_dev/dozzle.yml
  - docker/compose/services/_dev/vite.yml

# ──────────────────────────────────────────────────────────────────────────────────────────────
# 🕸️ Networks & Volumes
# ──────────────────────────────────────────────────────────────────────────────────────────────

networks:
  app-network:
    driver: bridge

volumes:
  pgadmin_data:
    driver: local
