sonar.projectKey=levelup-store
sonar.projectName=LevelUp Store

sonar.sources=src,assets/ts
sonar.tests=tests,assets/tests

sonar.exclusions=\
    vendor/**,\
    node_modules/**,\
    public/build/**,\
    var/**,\
    database/migrations/**

sonar.php.coverage.reportPaths=var/tools/php-unit/clover.xml

sonar.javascript.lcov.reportPaths=var/tools/vitest/coverage/lcov.info

sonar.eslint.reportPaths=var/tools/eslint/report.json
