graph TD
    %% Class Styles
    classDef testing fill:#000, color:#fff;
    classDef php-unit fill:#0637c0, color:#fff, stroke:#000, stroke-width:2px;
    classDef vitest fill:#f8ff59, color:#000, stroke:#000, stroke-width:2px;
    classDef playwright fill:#2EAD33, color:#fff, stroke:#000, stroke-width:2px;

    %% Root
    Testing[💻 Developer Environment]:::testing

    %% Testing tools
    PHPUnit[🧪 PHPUnit]:::php-unit
    Vitest[⚡ Vitest]:::vitest
    Playwright[🎭 Playwright]:::playwright

    %% Connections
    Testing --> PHPUnit
    Testing --> Vitest
    Testing --> Playwright
