apiVersion: v1
kind: Secret
metadata:
  name: {{ include "levelup-store-assistant.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "levelup-store-assistant.labels" . | nindent 4 }}
type: Opaque
stringData:
  AI_ASSISTANT_API_KEY: {{ required "app.aiAssistantApiKey is required" .Values.app.aiAssistantApiKey | quote }}
  REDIS_URL: {{ required "app.redisUrl is required" .Values.app.redisUrl | quote }}
  {{- if .Values.broker.enabled }}
  RABBITMQ_URL: {{ required "broker.rabbitmqUrl is required" .Values.broker.rabbitmqUrl | quote }}
  {{- end }}
