apiVersion: v1
kind: Secret
metadata:
  name: {{ include "levelup-store-assistant.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "levelup-store-assistant.labels" . | nindent 4 }}
type: Opaque
stringData:
  AI_ASSISTANT_API_KEY: {{ .Values.app.aiAssistantApiKey | quote }}
  REDIS_URL: {{ .Values.app.redisUrl | quote }}
  DATABASE_URL: {{ .Values.app.databaseUrl | quote }}
  API_KEY: {{ .Values.app.apiKey | quote }}
  {{- if .Values.broker.enabled }}
  RABBITMQ_URL: {{ .Values.broker.rabbitmqUrl | quote }}
  {{- end }}
