# ──────────────────────────────────────────────────────────────────────────────────────────────
# 📊 Observability - Prometheus
# ──────────────────────────────────────────────────────────────────────────────────────────────

services:
  prometheus:
    image: prom/prometheus:v3.14.0
    container_name: levelup_store_prometheus
    restart: unless-stopped
    volumes:
      - ${PWD}/docker/config/prometheus:/etc/prometheus:ro
      - prometheus_data:/prometheus
    ports:
      - '${PROMETHEUS_PORT}:9090'
    networks:
      - app-network
