# ──────────────────────────────────────────────────────────────────────────────────────────────
# 🐇 Message Broker - RabbitMQ 3
# ──────────────────────────────────────────────────────────────────────────────────────────────

services:
  rabbitmq:
    image: rabbitmq:4.3.5-management
    container_name: levelup_store_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    ports:
      - '${RABBITMQ_PORT}:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network
    extends:
      file: ../../_base/healthcheck.yml
      service: healthcheck-base
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
