# ──────────────────────────────────────────────────────────────────────────────────────────────
# ⚙️ Messenger Worker
# ──────────────────────────────────────────────────────────────────────────────────────────────

services:
  worker:
    extends:
      file: ../base.yml
      service: app-base
    container_name: levelup_store_worker
    restart: unless-stopped
    entrypoint: ['/usr/local/bin/scripts/entrypoints/app/worker/run-worker.sh']
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
