FROM jenkins/jenkins:lts

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
        docker.io \
    && curl -fsSL https://github.com/mikefarah/yq/releases/download/v4.53.6/yq_linux_amd64 \
        -o /usr/local/bin/yq \
    && chmod +x /usr/local/bin/yq \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
