apiVersion: v1
kind: Service
metadata:
  name: {{ include "levelup-store-assistant.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "levelup-store-assistant.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    {{- include "levelup-store-assistant.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
