apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "levelup-store.fullname" . }}
  labels:
    {{- include "levelup-store.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "levelup-store.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "levelup-store.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.securityContext.runAsNonRoot }}
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.securityContext.runAsUser }}
        fsGroup: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      containers:
        - name: app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: 8000
          securityContext:
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
            capabilities:
              drop: {{- toYaml .Values.securityContext.capabilities.drop | nindent 16 }}
          envFrom:
            - configMapRef:
                name: {{ include "levelup-store.fullname" . }}
            - secretRef:
                name: {{ include "levelup-store.fullname" . }}
          {{- if .Values.securityContext.readOnlyRootFilesystem }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: var-cache
              mountPath: /var/www/var/cache
            - name: var-log
              mountPath: /var/www/var/log
            - name: run
              mountPath: /run
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      {{- if .Values.securityContext.readOnlyRootFilesystem }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: var-cache
          emptyDir: {}
        - name: var-log
          emptyDir: {}
        - name: run
          emptyDir: {}
      {{- end }}
