apiVersion: v2
name: minio
description: MinIO object storage for LevelUp Store
type: application
version: 0.1.0
dependencies:
  - name: minio
    version: ">=14.0.0 <15.0.0"
    repository: https://charts.bitnami.com/bitnami
