apiVersion: v2
name: redis
description: Redis cache for LevelUp Store
type: application
version: 0.1.0
dependencies:
  - name: redis
    version: ">=19.0.0 <20.0.0"
    repository: https://charts.bitnami.com/bitnami
