{{- if not .Values.sealedSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "levelup-store.fullname" . }}
  labels:
    {{- include "levelup-store.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_SECRET: {{ .Values.app.secret | required "app.secret is required" | quote }}
  HMAC_SECRET: {{ .Values.app.hmacSecret | required "app.hmacSecret is required" | quote }}
  JWT_PASSPHRASE: {{ .Values.app.jwtPassphrase | required "app.jwtPassphrase is required" | quote }}

  DATABASE_URL: {{ .Values.app.databaseUrl | required "app.databaseUrl is required" | quote }}
  REDIS_URL: {{ .Values.app.redisUrl | required "app.redisUrl is required" | quote }}
  RABBITMQ_PASS: {{ .Values.app.rabbitmqPass | quote }}
  MESSENGER_TRANSPORT_DSN: {{ .Values.app.messengerDsn | required "app.messengerDsn is required" | quote }}

  MINIO_ROOT_USER: {{ .Values.app.minioRootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.app.minioRootPassword | quote }}
  MINIO_PUBLIC_URL: {{ .Values.minio.publicUrl | quote }}

  MERCURE_PUBLIC_URL: {{ .Values.mercure.publicUrl | quote }}
  MERCURE_JWT_SECRET: {{ .Values.app.mercureJwtSecret | required "app.mercureJwtSecret is required" | quote }}
  MERCURE_CORS_ORIGINS: {{ .Values.mercure.corsOrigins | quote }}

  TURNSTILE_SITE_KEY: {{ .Values.turnstile.siteKey | quote }}
  TURNSTILE_SECRET_KEY: {{ .Values.turnstile.secretKey | quote }}

  STRIPE_SECRET: {{ .Values.app.stripeSecret | required "app.stripeSecret is required" | quote }}
  MAILER_DSN: {{ .Values.app.mailerDsn | required "app.mailerDsn is required" | quote }}
{{- end }}
