# ──────────────────────────────────────────────────────────────────────────────────────────────
# 📘 Dev Tool - pgAdmin (PostgreSQL GUI)
# ──────────────────────────────────────────────────────────────────────────────────────────────

services:
  pgAdmin:
    image: dpage/pgadmin4:latest
    container_name: levelup_store_pgadmin
    restart: unless-stopped
    entrypoint: ['/bin/sh', '/pgadmin4/config/entrypoint.sh']
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      SERVER_VERSION: ${SERVER_VERSION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ${PWD}/docker/config/_dev/pgAdmin:/pgadmin4/config:ro
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
