# ──────────────────────────────────────────────────────────────────────────────────────────────
# 🟨 Dev Tool - Vite (Frontend Builder)
# ──────────────────────────────────────────────────────────────────────────────────────────────

services:
  vite:
    container_name: levelup_store_vite
    build:
      context: ${PWD}/docker/config/_dev/vite
      dockerfile: Dockerfile.vite
    working_dir: /var/www
    environment:
      CI: "true"
    command: sh -c "pnpm rebuild esbuild @parcel/watcher && pnpm run dev"
    volumes:
      - ${PWD}:/var/www
    ports:
      - '5173:5173'
    networks:
      - app-network
    depends_on:
      - app
