FROM node:24-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN pnpm config set store-dir /pnpm/store

WORKDIR /var/www

EXPOSE 5173

CMD ["pnpm", "run", "dev"]
