graph TD
    %% Class Styles
    classDef system fill:#000, color:#fff;
    classDef presentation fill:#0f63ff, color:#fff, stroke:#000, stroke-width:2px;
    classDef adapters fill:#f8ff59, color:#000, stroke:#000, stroke-width:2px;
    classDef application fill:#0a8555, color:#fff, stroke:#000, stroke-width:2px;
    classDef domain fill:#ff5c44, color:#fff, stroke:#000, stroke-width:2px;
    classDef ports fill:#8e44ad, color:#fff, stroke:#000, stroke-width:2px;
    classDef infrastructure fill:#ffa51c, color:#000, stroke:#000, stroke-width:2px;
    classDef shared fill:#d9dce0, color:#000, stroke:#000, stroke-width:2px;
    classDef scheduler fill:#27ae60, color:#fff, stroke:#000, stroke-width:2px;
    classDef bootstrap fill:#104f76, color:#fff, stroke:#000, stroke-width:2px;

    %% Root
    System[🧱 Architecture]:::system

    %% Layers and modules
    Bootstrap[🚀 Bootstrap]:::bootstrap
    Scheduler[⏰ Scheduler]:::scheduler
    Adapters[📦 Adapters]:::adapters
    Domain[🏛️ Domain]:::domain
    Application[⚙️ Application]:::application
    Ports[🔌 Ports]:::ports
    Infrastructure[🏢 Infrastructure]:::infrastructure
    Presentation[📱 Presentation]:::presentation
    Shared[📚 Shared]:::shared

    %% Connections
    System --> Bootstrap
    System --> Scheduler
    System --> Shared

    Domain --> Shared

    Adapters --> Ports
    Adapters --> Shared

    Application --> Domain
    Application --> Ports
    Application --> Infrastructure
    Application --> Shared

    Infrastructure --> Shared

    Presentation --> Application
    Presentation --> Infrastructure
    Presentation --> Shared
