nelmio_api_doc:
  documentation:
    info:
      title: LevelUp Store API
      description: REST API for LevelUp Store - ecommerce + admin panel
      version: 1.0.0
    components:
      securitySchemes:
        bearerAuth:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - bearerAuth: []

  areas:
    default:
      path_patterns:
        - ^/api(?!/doc$)
